# Generated by Django 4.0.4 on 2022-06-21 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_documental_pelicula_serie_delete_curso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documental',
            name='autor',
            field=models.CharField(default='Autor x', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pelicula',
            name='autor',
            field=models.CharField(default='Autor x', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serie',
            name='autor',
            field=models.CharField(default='Autor x', max_length=40),
            preserve_default=False,
        ),
    ]
