# Generated by Django 4.0.4 on 2022-06-30 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_documental_fecha_pelicula_fecha_serie_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documental',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='serie',
            name='fecha',
        ),
    ]
